//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Orders.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dispatch
    {
        public Dispatch()
        {
            this.WorkOrder = new HashSet<WorkOrder>();
        }
    
        public int id { get; set; }
        public string vendor { get; set; }
        public string dispatcher { get; set; }
        public string phone { get; set; }
        public string fax { get; set; }
        public string email { get; set; }
        public string tech { get; set; }
    
        public virtual ICollection<WorkOrder> WorkOrder { get; set; }
    }
}
