//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Orders.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ReportEntities : DbContext
    {
        public ReportEntities()
            : base("name=ReportEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Accounting> Accounting { get; set; }
        public DbSet<Clients> Clients { get; set; }
        public DbSet<Dispatch> Dispatch { get; set; }
        public DbSet<Divisions> Divisions { get; set; }
        public DbSet<JobStatus> JobStatus { get; set; }
        public DbSet<Material> Material { get; set; }
        public DbSet<Order> Order { get; set; }
        public DbSet<Paids> Paids { get; set; }
        public DbSet<PMS> PMS { get; set; }
        public DbSet<Priority> Priority { get; set; }
        public DbSet<Requests> Requests { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<Technician> Technician { get; set; }
        public DbSet<Totals> Totals { get; set; }
    }
}
