//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections;
using System.Linq;

namespace Orders.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderMaterials
    {
        public int Material_id { get; set; }
        public Nullable<decimal> quantity { get; set; }
        public int id { get; set; }
        public Nullable<int> Order_id { get; set; }
    
        public virtual Material Material { get; set; }
        public virtual WorkOrder WorkOrder { get; set; }
    }

    public static class Mydataprovider
    {
        static ReportEntities re = new ReportEntities();

        public static IEnumerable GetCategories()
        {
            var query = from material in re.Material
                        select new
                        {
                            Material_id = material.Material_id,
                            CategoryName = material.name,

                        };
            return query.ToList();
        }

    }
}
