//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Orders.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Requests
    {
        public Requests()
        {
            this.WorkOrder = new HashSet<WorkOrder>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
    
        public virtual ICollection<WorkOrder> WorkOrder { get; set; }
    }
}
