//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Orders.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Technician
    {
        public Technician()
        {
            this.WorkOrder = new HashSet<WorkOrder>();
        }
    
        public int id { get; set; }
        public Nullable<bool> obtainedSig { get; set; }
        public string notesFromTech { get; set; }
        public Nullable<bool> exceededNTE { get; set; }
        public string ProblemFound { get; set; }
        public string multipleCheckInOut { get; set; }
    
        public virtual ICollection<WorkOrder> WorkOrder { get; set; }
    }
}
