//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Orders.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Totals
    {
        public int id { get; set; }
        public Nullable<decimal> totalTechs { get; set; }
        public Nullable<decimal> totalHours { get; set; }
        public Nullable<decimal> trip { get; set; }
        public Nullable<decimal> totalLabor { get; set; }
        public Nullable<decimal> tax { get; set; }
        public Nullable<decimal> totalItems { get; set; }
        public Nullable<decimal> totalMaterials { get; set; }
        public Nullable<decimal> taxMaterials { get; set; }
        public Nullable<decimal> grandTotal { get; set; }
        public Nullable<decimal> totalDiscount { get; set; }
        public Nullable<decimal> toalThisPropsal { get; set; }
        public int orderid { get; set; }
    
        public virtual WorkOrder WorkOrder { get; set; }
    }
}
