//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Orders.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Totals
    {
        public int id { get; set; }
        public Nullable<double> totalTechs { get; set; }
        public Nullable<double> totalHours { get; set; }
        public Nullable<double> trip { get; set; }
        public Nullable<double> totalLabor { get; set; }
        public Nullable<double> tax { get; set; }
        public Nullable<double> totalItems { get; set; }
        public Nullable<double> totalMaterials { get; set; }
        public Nullable<double> taxMaterials { get; set; }
        public Nullable<double> grandTotal { get; set; }
        public Nullable<double> totalDiscount { get; set; }
        public Nullable<double> toalThisPropsal { get; set; }
        public int orderid { get; set; }
    
        public virtual Order Order { get; set; }
    }
}
