//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Orders.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkOrder
    {
        public WorkOrder()
        {
            this.OrderMaterials = new HashSet<OrderMaterials>();
            this.Paids = new HashSet<Paids>();
            this.Totals = new HashSet<Totals>();
        }
    
        public string number { get; set; }
        public int id { get; set; }
        public Nullable<int> divisionId { get; set; }
        public Nullable<int> clientId { get; set; }
        public Nullable<int> priorityId { get; set; }
        public Nullable<int> requestId { get; set; }
        public string poNumber { get; set; }
        public string nte { get; set; }
        public string jobSite { get; set; }
        public string phone { get; set; }
        public string jobSiteContact { get; set; }
        public string adress { get; set; }
        public Nullable<int> cityId { get; set; }
        public string stateZip { get; set; }
        public string siteRegion { get; set; }
        public string problemType { get; set; }
        public Nullable<System.DateTime> woDate { get; set; }
        public string requestedBy { get; set; }
        public Nullable<int> jobstatusId { get; set; }
        public string dispatchedBy { get; set; }
        public Nullable<System.DateTime> datePromised { get; set; }
        public Nullable<System.DateTime> dateCompleted { get; set; }
        public Nullable<decimal> laborHours { get; set; }
        public string vendor { get; set; }
        public string techPhone { get; set; }
        public string fax { get; set; }
        public string jobdescription { get; set; }
        public Nullable<int> dispatchId { get; set; }
        public Nullable<int> pmsId { get; set; }
        public Nullable<int> accountingId { get; set; }
        public Nullable<int> technicianId { get; set; }
        public string labor { get; set; }
        public string multimpleassets { get; set; }
        public string notes { get; set; }
    
        public virtual Accounting Accounting { get; set; }
        public virtual Citys Citys { get; set; }
        public virtual Clients Clients { get; set; }
        public virtual Dispatch Dispatch { get; set; }
        public virtual Divisions Divisions { get; set; }
        public virtual JobStatus JobStatus { get; set; }
        public virtual ICollection<OrderMaterials> OrderMaterials { get; set; }
        public virtual ICollection<Paids> Paids { get; set; }
        public virtual PMS PMS { get; set; }
        public virtual Priority Priority { get; set; }
        public virtual Requests Requests { get; set; }
        public virtual Technician Technician { get; set; }
        public virtual ICollection<Totals> Totals { get; set; }
    }
}
